POST https://afternoon-basin-88260.herokuapp.com/api/products/
Content-Type: application/json

{
    "name": "Product3",
    "productId": "Product3Id",
    "description": "Product3Description",
    "brand": "Product3Brand",
    "price": 35,
    "stock": 32,
    "suppliers": "Product3Supplier3
}